<div class="page-header"style="margin-top:100px;margin-bottom:50px;">
    <h1><span>Sistem Pendataan Bantuan Pandemi Covid-19</span></h1>
</div>

<div class="page-header"style="margin-bottom:50px;">
<p>Sebuah Website Sistem Informasi data bantuan pandemi Covid-19. 
Setiap orang dapat registrasi dan dapat memberikan bantuan, 
terdapat berbagai jenis bantuan, seperti uang, bahan makanan dan sebagainya. 
Setiap transaksi bantuan boleh lebih dari satu bantuan. 
Pada sistem ini, user dapat melihat daftar rekap bantuan yang tersedia berdasarkan kategori atau jenis bantuan.</p>
</div>
<?php
echo $this->tag->linkTo ([
    "transaksi/uang","class" => "btn btn-info",
    "Daftar Rekap Bantuan Berdasarkan Kategori"]
);?>
